// Generated by CoffeeScript 1.6.3
describe('TripModel', function() {
  var trip;
  trip = null;
  beforeEach(function() {
    return trip = new TripModel();
  });
  it('can convert degrees to radians', function() {
    var result;
    result = TripModel.toRad(90).toFixed(2);
    return expect(result).toBe('1.57');
  });
  it('should set and get origin coords', function() {
    trip.setOriginCoords([1, 2]);
    expect(trip.getOriginCoords()[0]).toBe(1);
    return expect(trip.getOriginCoords()[1]).toBe(2);
  });
  it('should set and get destination', function() {
    trip.setDestinationCoords([1, 2]);
    expect(trip.getDestinationCoords()[0]).toBe(1);
    return expect(trip.getDestinationCoords()[1]).toBe(2);
  });
  return it('should calculate the distance between two Geographic Coordinates', function() {
    var result;
    trip.setOriginCoords([35, -106]);
    trip.setDestinationCoords([38, -76]);
    result = trip.calculateDistance();
    return expect(result).toBe(1453);
  });
});
