// Generated by CoffeeScript 1.6.3
var TripModel;

TripModel = (function() {
  var data, destinationCoords, originCoords;

  function TripModel() {}

  data = {};

  originCoords = [0.0, 0.0];

  destinationCoords = [0.0, 0.0];

  TripModel.toRad = function(degrees) {
    return degrees * Math.PI / 180;
  };

  TripModel.prototype.setOriginCoords = function(coords) {
    return this.originCoords = coords.slice();
  };

  TripModel.prototype.getOriginCoords = function() {
    return this.originCoords;
  };

  TripModel.prototype.setDestinationCoords = function(coords) {
    return this.destinationCoords = coords.slice();
  };

  TripModel.prototype.getDestinationCoords = function() {
    return this.destinationCoords;
  };

  TripModel.prototype.calculateDistance = function() {
    var RADIUS, a, c, d, lat1, lat2, long1, long2;
    RADIUS = 6371 * 0.539957;
    lat1 = TripModel.toRad(this.originCoords[0]);
    long1 = TripModel.toRad(this.originCoords[1]);
    lat2 = TripModel.toRad(this.destinationCoords[0]);
    long2 = TripModel.toRad(this.destinationCoords[1]);
    a = Math.sin((lat2 - lat1) / 2) * Math.sin((lat2 - lat1) / 2) + Math.sin((long2 - long1) / 2) * Math.sin((long2 - long1) / 2) * Math.cos(lat1) * Math.cos(lat2);
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return d = Math.round(RADIUS * c);
  };

  return TripModel;

})();

this.TripModel = TripModel;
