// Generated by CoffeeScript 1.6.3
var ViewController;

ViewController = (function() {
  var data;

  data = {};

  function ViewController(file_location) {
    var _this = this;
    $.getJSON(file_location, function(data) {
      return _this.data = data;
    });
  }

  ViewController.updateDistance = function(dom_elem, value) {
    return dom_elem.text(value + " km");
  };

  ViewController.prototype.getCoords = function(code) {
    var coords;
    coords = [];
    coords[0] = data[code]["lat"];
    coords[1] = data[code]["long"];
    return coords;
  };

  ViewController.prototype.getData = function() {
    return this.data;
  };

  ViewController.prototype.setData = function(json) {
    return this.data = json;
  };

  return ViewController;

})();

this.ViewController = ViewController;
